

services:

  db:
    image: postgres
    build: 
      context: database
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgresdb
      POSTGRES_DB: bank
    volumes:
      - pg_data:/var/lib/postgresql/data

  bank:
    image: bank
    restart: always
    build:
      context: bank_api
      dockerfile: Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:postgresdb@db/bank
    ports:
      - 9000:9000
    depends_on:
      - db
      
    

volumes:
  pg_data:
    

  
